# Generated by Django 3.1.2 on 2021-01-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201226_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
